# Catálogo de produtos
PRODUCT_CATALOG = {
    "ATIVAR APP": [
        {"name": "➕​ ASSIST+ R$ 65", "price": 65.00, "fields": ["MAC"]},
        {"name": "📱 NINJA PLAYER R$65", "price": 65.00, "fields": ["MAC", "CHAVE OTP"]},
        {"name": "📺 MEGA IPTV R$ 75", "price": 75.00, "fields": ["MAC"]},
        {"name": "🧠 SMART ONE R$60", "price": 70.00, "fields": ["MAC"]},
        {"name": "🎮 IBO PRO PLAYER R$50", "price": 50.00, "fields": ["MAC"]},
        {"name": "📡 IBO TV OFICIAL R$50", "price": 50.00, "fields": ["MAC"]},
        {"name": "🧩 DUPLECAST R$60", "price": 60.00, "fields": ["MAC", "CHAVE OTP"]},
        {"name": "🌐 BAY TV R$60", "price": 60.00, "fields": ["MAC"]},
        {"name": "🟣​ QUICK PLAYER R$65", "price": 65.00, "fields": ["MAC"]},
        {"name": "▶️​ TIVI PLAYER R$65", "price": 65.00, "fields": ["MAC"]},
        {"name": "🔥 SUPER PLAY R$50", "price": 50.00, "fields": ["MAC"]},
        {"name": "☁️ CLOUDDY R$65", "price": 65.00, "fields": ["E-mail", "Senha do app"]},
    ],
    "COMPRAR CRÉDITOS": [
        {"name": "🎯 X SERVER PLAY (13,50und)", "price": 13.50, "discount": True},
        {"name": "⚡ FAST PLAYER (13,50und)", "price": 13.50, "discount": True},
        {"name": "👑 GOLD PLAY (13,50und)", "price": 13.50, "discount": True},
        {"name": "📺 EI TV (13,50und)", "price": 13.50, "discount": True},
        {"name": "🛰️ Z TECH (13,50und)", "price": 13.50, "discount": True},
        {"name": "🧠 GENIAL PLAY (13,50und)", "price": 13.50, "discount": True},
        {"name": "🚀 UPPER PLAY (15,00und)", "price": 150.00, "discount": False},
    ],
